### ISSUE TITLE
play.py error

### ISSUE THREAD

**Issue by bfcb** [dakaugu/hqtrivia#3]
installed terresact and added to path.

Traceback (most recent call last):
  File "C:\Users\jaysun\Desktop\hqtrivia-master\play.py", line 116, in <module>
    feed(img)
  File "C:\Users\jaysun\Desktop\hqtrivia-master\play.py", line 86, in feed
    question, answers = text.split("?")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dakaugu** [comment]
Make sure to run rec.py to determine what portion of the screen you are grabbing an image and change bbox values accordingly

**Comment by bfcb** [comment]
i run it but it crashes immediately. I have set both bbox to same values on rec.py and play.py

edit. nvm i got the bbox to optimal settings on both. now it works.
